[env:arduino-ros]
platform = espressif32
board = esp32dev
framework = arduino
board_microros_distro = humble
# board_microros_transport = wifi
board_microros_transport = serial
board_build.filesystem = littlefs
# Fuerza a que busque dependencias en cada archivo
lib_ldf_mode = chain+ 
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/adrianmarino/arduino-commons
    https://github.com/tzapu/WiFiManager
    WiFi
build_flags = -I ../../include -ffunction-sections -fdata-sections